### ISSUE TITLE
WebDev Projects.

### ISSUE THREAD

**Issue by akbar-alam** [manjunani/HacktoberFest_2021#11]
I have added a my project to webdev section. Who will be reviewing it my pull request has passes all the test but it didn't got merge into main repo.

**Comment by manjunani** [comment]
Yeah I will be verifying and merge into the main branch

**Comment by akbar-alam** [comment]
> Yeah I will be verifying and merge into the main branch
On my hacktoberfest profile it says "Project not participating".
