### ISSUE TITLE
Add while loop

### ISSUE THREAD

**Issue by arunagri82** [manjunani/HacktoberFest_2021#13]
#include <stdio.h>
int binarySearch(int arr[], int l, int r, int x)
{
	while (l <= r) {
		int m = l + (r - l) / 2;
		if (arr[m] == x)
			return m;
		if (arr[m] < x)
			l = m + 1;
		else
			r = m - 1;
	}
	return -1;
}

int main(void)
{
	int arr[] = { 2, 3, 4, 10, 40 };
	int n = sizeof(arr) / sizeof(arr[0]);
	int x = 10;
	int result = binarySearch(arr, 0, n - 1, x);
	if(result == -1)
	printf("Element is not present in array");
  else
  printf("Element is present at index %d",result);
	return 0;
}

**Comment by manjunani** [comment]
I Suggest you to kindly keep the code in a file and  add that respective file in the respective folder. Do check out the readme File.
