### ISSUE TITLE
DSA Python Codes

### ISSUE THREAD

**Issue by manjunani** [manjunani/HacktoberFest_2021#3]

**Comment by akbar-alam** [comment]
Hi there! I'm looking into an issues and the issue says "No description provided".

**Comment by tandrimasingha** [comment]
Name: Tandrima Singha
Domain: Python
Hello @manjunani Sir , I want to do this 
can you please assign this to me and tell what to do

**Comment by manjunani** [comment]
Hi @tandrimasingha  The Issue has been assigned on your name. Kindly Go ahead with the Changes

**Comment by arushmangal** [comment]
Can I add solutions to some DSA Problems that I solved on HackerRank and CodeChef?

**Comment by tandrimasingha** [comment]
Name: Tandrima Singha
Domain: Python
Hello @manjunani  Sir , I want to do this
can you please assign this to me and tell what to do

**Comment by manjunani** [comment]
Hi @arushmangal, Yeah sure kindly add the programs in the DSA/Python folder and do update the description of that program in readme file.

**Comment by tandrimasingha** [comment]
@manjunani Sir Is this hacktober2021 program. Will this be counted there

**Comment by manjunani** [comment]
@tandrimasingha , you can check the count of PR's that you raised for this repo and the status in your hacktoberfest profile 
Note: If Some Organizers from Hacktoberfest Team find's this as a Spam then the repo is marked as spam and then these PR's are not valid. So, **I am making sure that there wont be any spam PR's created and other spam issues with the PR's that has been created by all.

**Comment by manjunani** [comment]
and @tandrimasingha  for you  request of 
**
Name: Tandrima Singha
Domain: Python
Hello @manjunani Sir , I want to do this can you please assign this to me and tell what to do
**
I suggest you to create some new Algorithms and add to the Repo.. in your favorite language and update the readme too
some of the Algorithms 
ex.
Dijkstra Algorithm,
Prim's Algorithm,
Dining Philosopher's Problem,
0/1 Knapsack Problem,
etc..

**Comment by tandrimasingha** [comment]
Sir I would like to do Data Structure. Shall I move forward with that

**Comment by manjunani** [comment]
Yeah Sure, Go Ahead
