### ISSUE TITLE
Add Solar System Simulation

### ISSUE THREAD

**Issue by arushmangal** [manjunani/HacktoberFest_2021#33]
I made a simulation of the Solar System with Unity Game Developer and wanted to ask if I could upload it onto this repository considering you'd be interested. @manjunani

**Comment by manjunani** [comment]
Yeah, Go ahead with the changes  @arushmangal

**Comment by arushmangal** [comment]
Sure! I'll just take some time to finish up and polish the simulation and then I'll send a PR!

**Comment by arushmangal** [comment]
Done! @manjunani
